/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        'on-secondary-fixed': '#2c0051',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'tertiary-container': '#00f7a6',
        'surface-variant': '#353436',
        'on-background': '#e5e2e3',
        'on-tertiary-container': '#006c46',
        'inverse-surface': '#e5e2e3',
        'secondary': '#dcb8ff',
        'secondary-fixed-dim': '#dcb8ff',
        'primary': '#dbfcff',
        'surface-container': '#201f20',
        'on-secondary-fixed-variant': '#6700b5',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#002022',
        'surface': '#131314',
        'error-container': '#93000a',
        'secondary-container': '#7701d0',
        'on-tertiary': '#003822',
        'primary-container': '#00f0ff',
        'primary-fixed-dim': '#00dbe9',
        'on-primary-fixed-variant': '#004f54',
        'on-secondary-container': '#dcb7ff',
        'inverse-on-surface': '#313031',
        'outline': '#849495',
        'tertiary-fixed-dim': '#00e297',
        'on-tertiary-fixed': '#002112',
        'on-tertiary-fixed-variant': '#005234',
        'surface-container-high': '#2a2a2b',
        'secondary-fixed': '#efdbff',
        'tertiary-fixed': '#4dffb2',
        'on-surface': '#e5e2e3',
        'surface-dim': '#131314',
        'tertiary': '#d7ffe5',
        'on-primary-container': '#006970',
        'on-primary': '#00363a',
        'surface-tint': '#00dbe9',
        'surface-container-highest': '#353436',
        'on-surface-variant': '#b9cacb',
        'primary-fixed': '#7df4ff',
        'outline-variant': '#3b494b',
        'surface-container-lowest': '#0e0e0f',
        'background': '#131314',
      },
      fontFamily: {
        'sans': ['Space Grotesk', 'Inter', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
}